# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dido\Desktop\New Control\final_Control_portrait_darker.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(411, 992)
        Dialog.setStyleSheet("QDialog#Dialog{\n"
"background-color: rgb(26, 8, 97);\n"
"}")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(210, 90, 181, 131))
        self.label_3.setStyleSheet("background-color: rgb(230,156,156);    border-radius:13px;\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(260, 100, 71, 71))
        self.label_4.setStyleSheet("background-color: rgb(230,156,156);\n"
"border-image: url(res/icons8-stop-60.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(210, 370, 181, 131))
        self.label_21.setStyleSheet("background-color: rgb(96,245,235);    border-radius:13px;\n"
"")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("\n"
"QPushButton#pushButton_3{\n"
"    \n"
"color:rgb(0,0,0);\n"
"    border-radius:13px;\n"
"}\n"
"\n"
"QPushButton#pushButton_3:hover{\n"
"    background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgb(0,0,0),stop:1 rgba(85,81,84,226));\n"
"    color:rgba(255,255,255,210);\n"
"}\n"
"\n"
"QPushButton#pushButton_3:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(270, 380, 61, 61))
        self.label_22.setStyleSheet("border-image: url(res/icons8-report-64_1.png);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 370, 181, 131))
        self.label_9.setStyleSheet("background-color: rgb(242,24,24);    border-radius:13px;\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.pushButton_12 = QtWidgets.QPushButton(Dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(240, 460, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("\n"
"QPushButton#pushButton_12{\n"
"    \n"
"color:rgb(0,0,0);\n"
"    border-radius:13px;\n"
"}\n"
"\n"
"QPushButton#pushButton_12:hover{\n"
"    background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgb(0,0,0),stop:1 rgba(85,81,84,226));\n"
"    color:rgba(255,255,255,210);\n"
"}\n"
"\n"
"QPushButton#pushButton_12:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(210, 230, 181, 131))
        self.label_7.setStyleSheet("background-color: rgb(140,205,247);    border-radius:13px;\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_31 = QtWidgets.QLabel(Dialog)
        self.label_31.setGeometry(QtCore.QRect(210, 720, 181, 61))
        self.label_31.setStyleSheet("background-color: rgb(176,196,222);    border-radius:13px;\n"
"")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 90, 181, 131))
        self.label.setStyleSheet("background-color: rgb(164, 115, 198);    border-radius:13px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_32 = QtWidgets.QLabel(Dialog)
        self.label_32.setGeometry(QtCore.QRect(220, 730, 51, 51))
        self.label_32.setStyleSheet("\n"
"border-image: url(res/icons8-logout-64.png);")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 230, 181, 131))
        self.label_5.setStyleSheet("background-color: rgb(255,223,58);    border-radius:13px;\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(70, 380, 71, 71))
        self.label_10.setStyleSheet("background-color: rgb(242,24,24);border-image: url(res/icons8-emergency-64_2.png);\n"
"border-image: url(res/icons8-sos-64_1.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setGeometry(QtCore.QRect(20, 650, 181, 131))
        self.label_29.setStyleSheet("background-color: rgb(153,204,255);    border-radius:13px;\n"
"")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 100, 71, 71))
        self.label_2.setStyleSheet("background-color: rgb(164, 115, 198);\n"
"border-image: url(res/icons8-start-64.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 460, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("\n"
"QPushButton#pushButton_6{\n"
"    \n"
"color:rgb(0,0,0);\n"
"    border-radius:13px;\n"
"}\n"
"\n"
"QPushButton#pushButton_6:hover{\n"
"    background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgb(0,0,0),stop:1 rgba(85,81,84,226));\n"
"    color:rgba(255,255,255,210);\n"
"}\n"
"\n"
"QPushButton#pushButton_6:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(20, 510, 181, 131))
        self.label_23.setStyleSheet("background-color: rgb(255,255,255);    border-radius:13px;\n"
"")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_30 = QtWidgets.QLabel(Dialog)
        self.label_30.setGeometry(QtCore.QRect(80, 660, 61, 61))
        self.label_30.setStyleSheet("\n"
"border-image: url(res/icons8-shutdown-48_1.png);")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_39 = QtWidgets.QLabel(Dialog)
        self.label_39.setGeometry(QtCore.QRect(210, 510, 181, 131))
        self.label_39.setStyleSheet("background-color: rgb(229,204,255);    border-radius:13px;\n"
"")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(80, 240, 71, 71))
        self.label_6.setStyleSheet("\n"
"border-image: url(res/icons8-emergency-64_2.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(60, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("\n"
"QPushButton#pushButton_7{\n"
"    \n"
"color:rgb(0,0,0);\n"
"    border-radius:13px;\n"
"}\n"
"\n"
"QPushButton#pushButton_7:hover{\n"
"    background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgb(0,0,0),stop:1 rgba(85,81,84,226));\n"
"    color:rgba(255,255,255,210);\n"
"}\n"
"\n"
"QPushButton#pushButton_7:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_15 = QtWidgets.QPushButton(Dialog)
        self.pushButton_15.setGeometry(QtCore.QRect(210, 610, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("\n"
"QPushButton#pushButton_15{\n"
"    \n"
"    color:rgb(0,0,0);\n"
"    border-radius:13px;\n"
"}\n"
"\n"
"QPushButton#pushButton_15:hover{\n"
"    background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgb(0,0,0),stop:1 rgba(85,81,84,226));\n"
"    color:rgba(255,255,255,210);\n"
"}\n"
"\n"
"QPushButton#pushButton_15:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(90, 530, 61, 61))
        self.label_25.setStyleSheet("\n"
"border-image: url(res/icons8-train-64_1.png);")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_41 = QtWidgets.QLabel(Dialog)
        self.label_41.setGeometry(QtCore.QRect(270, 530, 61, 61))
        self.label_41.setStyleSheet("border-image: url(res/icons8-train-64_2.png);")
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.pushButton_16 = QtWidgets.QPushButton(Dialog)
        self.pushButton_16.setGeometry(QtCore.QRect(30, 610, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("\n"
"QPushButton#pushButton_16{\n"
"    \n"
"color:rgb(0,0,0);\n"
"    border-radius:13px;\n"
"}\n"
"\n"
"QPushButton#pushButton_16:hover{\n"
"    background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgb(0,0,0),stop:1 rgba(85,81,84,226));\n"
"    color:rgba(255,255,255,210);\n"
"}\n"
"\n"
"QPushButton#pushButton_16:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_20 = QtWidgets.QPushButton(Dialog)
        self.pushButton_20.setGeometry(QtCore.QRect(30, 740, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("\n"
"QPushButton#pushButton_20{\n"
"    \n"
"    color:rgb(0,0,0);\n"
"    border-radius:13px;\n"
"}\n"
"\n"
"QPushButton#pushButton_20:hover{\n"
"    background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgb(0,0,0),stop:1 rgba(85,81,84,226));\n"
"    color:rgba(255,255,255,210);\n"
"}\n"
"\n"
"QPushButton#pushButton_20:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_22 = QtWidgets.QPushButton(Dialog)
        self.pushButton_22.setGeometry(QtCore.QRect(290, 730, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("\n"
"QPushButton#pushButton_22{\n"
"    \n"
"    color:rgb(0,0,0);\n"
"    border-radius:13px;\n"
"}\n"
"\n"
"QPushButton#pushButton_22:hover{\n"
"    background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgb(0,0,0),stop:1 rgba(85,81,84,226));\n"
"    color:rgba(255,255,255,210);\n"
"}\n"
"\n"
"QPushButton#pushButton_22:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.pushButton_22.setObjectName("pushButton_22")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(260, 230, 71, 71))
        self.label_11.setStyleSheet("background-color: rgb(140,205,247);\n"
"border-image: url(res/icons8-emergency-64.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(250, 320, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("\n"
"QPushButton#pushButton_8{\n"
"    \n"
"background-color: rgb(140,205,247);\n"
"    color:rgb(0,0,0);\n"
"    border-radius:13px;\n"
"}\n"
"\n"
"QPushButton#pushButton_8:hover{\n"
"    background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0  rgb(0,0,0),stop:1 rgba(85,81,84,226));\n"
"    color:rgba(255,255,255,210);\n"
"}\n"
"\n"
"QPushButton#pushButton_8:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(50, 320, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("\n"
"QPushButton#pushButton_9{\n"
"    \n"
"\n"
"    color:rgb(0,0,0);\n"
"    border-radius:13px;\n"
"}\n"
"\n"
"QPushButton#pushButton_9:hover{\n"
"    background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgb(0,0,0),stop:1 rgba(85,81,84,226));\n"
"    color:rgba(255,255,255,210);\n"
"}\n"
"\n"
"QPushButton#pushButton_9:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_54 = QtWidgets.QLabel(Dialog)
        self.label_54.setGeometry(QtCore.QRect(340, 900, 41, 16))
        self.label_54.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(Dialog)
        self.label_55.setGeometry(QtCore.QRect(80, 860, 41, 16))
        self.label_55.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(Dialog)
        self.label_56.setGeometry(QtCore.QRect(120, 860, 41, 16))
        self.label_56.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(Dialog)
        self.label_57.setGeometry(QtCore.QRect(280, 860, 41, 16))
        self.label_57.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_57.setObjectName("label_57")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(20, 960, 361, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_58 = QtWidgets.QLabel(Dialog)
        self.label_58.setGeometry(QtCore.QRect(200, 860, 41, 16))
        self.label_58.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(Dialog)
        self.label_59.setGeometry(QtCore.QRect(50, 860, 41, 16))
        self.label_59.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_59.setObjectName("label_59")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(40, 940, 81, 20))
        self.checkBox.setStyleSheet("color: rgb(225, 225, 225);")
        self.checkBox.setObjectName("checkBox")
        self.label_60 = QtWidgets.QLabel(Dialog)
        self.label_60.setGeometry(QtCore.QRect(40, 910, 41, 16))
        self.label_60.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_60.setObjectName("label_60")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(20, 830, 361, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(10, 840, 20, 131))
        self.line_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_61 = QtWidgets.QLabel(Dialog)
        self.label_61.setGeometry(QtCore.QRect(240, 860, 41, 16))
        self.label_61.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(Dialog)
        self.label_62.setGeometry(QtCore.QRect(160, 860, 41, 16))
        self.label_62.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_62.setObjectName("label_62")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(370, 840, 16, 131))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(50, 880, 311, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(30, 30, 171, 41))
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setPlaceholderText("")
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(210, 30, 181, 41))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_63 = QtWidgets.QLabel(Dialog)
        self.label_63.setGeometry(QtCore.QRect(20, 790, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_63.setObjectName("label_63")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 230, 181, 131))
        self.label_8.setStyleSheet("background-color:rgba(0,0,0,40);\n"
"border-radius:13px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(210, 370, 181, 131))
        self.label_12.setStyleSheet("background-color:rgba(0,0,0,40);\n"
"border-radius:13px;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(210, 510, 181, 131))
        self.label_14.setStyleSheet("background-color:rgba(0,0,0,40);\n"
"border-radius:13px;")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(20, 650, 181, 131))
        self.label_15.setStyleSheet("background-color:rgba(0,0,0,40);\n"
"border-radius:13px;")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_33 = QtWidgets.QLabel(Dialog)
        self.label_33.setGeometry(QtCore.QRect(210, 650, 181, 61))
        self.label_33.setStyleSheet("background-color: rgb(255,153,51);    border-radius:13px;\n"
"")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(20, 510, 181, 131))
        self.label_16.setStyleSheet("background-color:rgba(0,0,0,40);\n"
"border-radius:13px;")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_34 = QtWidgets.QLabel(Dialog)
        self.label_34.setGeometry(QtCore.QRect(220, 660, 41, 41))
        self.label_34.setStyleSheet("\n"
"border-image: url(res/delete.png);")
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.pushButton_23 = QtWidgets.QPushButton(Dialog)
        self.pushButton_23.setGeometry(QtCore.QRect(270, 660, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("\n"
"QPushButton#pushButton_23{\n"
"    \n"
"    color:rgb(0,0,0);\n"
"    border-radius:13px;\n"
"}\n"
"\n"
"QPushButton#pushButton_23:hover{\n"
"    background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgb(0,0,0),stop:1 rgba(85,81,84,226));\n"
"    color:rgba(255,255,255,210);\n"
"}\n"
"\n"
"QPushButton#pushButton_23:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.label_64 = QtWidgets.QLabel(Dialog)
        self.label_64.setGeometry(QtCore.QRect(310, 860, 41, 16))
        self.label_64.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(Dialog)
        self.label_65.setGeometry(QtCore.QRect(340, 860, 41, 16))
        self.label_65.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_65.setObjectName("label_65")
        self.label_23.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_21.raise_()
        self.pushButton_3.raise_()
        self.label_22.raise_()
        self.label_9.raise_()
        self.label_7.raise_()
        self.label_31.raise_()
        self.label.raise_()
        self.label_32.raise_()
        self.label_5.raise_()
        self.label_10.raise_()
        self.label_29.raise_()
        self.label_2.raise_()
        self.pushButton_6.raise_()
        self.label_39.raise_()
        self.pushButton_7.raise_()
        self.label_11.raise_()
        self.pushButton_8.raise_()
        self.label_54.raise_()
        self.label_55.raise_()
        self.label_56.raise_()
        self.label_57.raise_()
        self.line_3.raise_()
        self.label_58.raise_()
        self.label_59.raise_()
        self.checkBox.raise_()
        self.label_60.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.label_61.raise_()
        self.label_62.raise_()
        self.line_2.raise_()
        self.horizontalSlider.raise_()
        self.comboBox.raise_()
        self.comboBox_2.raise_()
        self.label_63.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.pushButton_9.raise_()
        self.label_12.raise_()
        self.pushButton_12.raise_()
        self.pushButton_22.raise_()
        self.label_14.raise_()
        self.label_41.raise_()
        self.pushButton_15.raise_()
        self.label_15.raise_()
        self.label_30.raise_()
        self.pushButton_20.raise_()
        self.label_33.raise_()
        self.label_16.raise_()
        self.pushButton_16.raise_()
        self.label_25.raise_()
        self.label_34.raise_()
        self.pushButton_23.raise_()
        self.label_64.raise_()
        self.label_65.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Control"))
        Dialog.setWindowIcon(QtGui.QIcon("picture2.png"))
        self.pushButton_3.setText(_translate("Dialog", "Stop"))
        self.pushButton_12.setText(_translate("Dialog", "Reports"))
        self.pushButton_6.setText(_translate("Dialog", "S.O.S"))
        self.pushButton_7.setText(_translate("Dialog", "Start"))
        self.pushButton_15.setText(_translate("Dialog", "Add Train WestBound"))
        self.pushButton_16.setText(_translate("Dialog", "Add Train EastBound"))
        self.pushButton_20.setText(_translate("Dialog", "Terminate Process"))
        self.pushButton_22.setText(_translate("Dialog", "Logout"))
        self.pushButton_8.setText(_translate("Dialog", "Reroute"))
        self.pushButton_9.setText(_translate("Dialog", "Emergency"))
        self.label_54.setText(_translate("Dialog", "Max"))
        self.label_55.setText(_translate("Dialog", "10"))
        self.label_56.setText(_translate("Dialog", "20"))
        self.label_57.setText(_translate("Dialog", "60"))
        self.label_58.setText(_translate("Dialog", "40"))
        self.label_59.setText(_translate("Dialog", "0"))
        self.checkBox.setText(_translate("Dialog", "Select All"))
        self.label_60.setText(_translate("Dialog", "Min"))
        self.label_61.setText(_translate("Dialog", "50"))
        self.label_62.setText(_translate("Dialog", "30"))
        self.label_63.setText(_translate("Dialog", "Speed Control"))
        self.pushButton_23.setText(_translate("Dialog", "Remove Train"))
        self.label_64.setText(_translate("Dialog", "70"))
        self.label_65.setText(_translate("Dialog", "80"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
